# Generated by Django 4.2.1 on 2023-08-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='for_app',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
