# Generated by Django 4.2.1 on 2023-08-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_permission_for_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='color',
            field=models.CharField(default='#04a9f5', max_length=7),
        ),
    ]
