# Generated by Django 4.2.1 on 2023-08-09 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('expected_end_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('revisions', models.PositiveIntegerField(default=0)),
                ('fields', models.JSONField(blank=True, null=True)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_assessments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='components.client')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentVulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('target', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
                ('cvss', models.FloatField(blank=True, null=True)),
                ('risk_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('remediation', models.TextField(blank=True, null=True)),
                ('poc_text', models.TextField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities_w', to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='CKImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ck_image_uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilityScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vulnerabilityscreenshot/')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='assessments.assessmentvulnerability')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessmentvulnerability',
            name='poc_screenshots',
            field=models.ManyToManyField(blank=True, related_name='vulnerabilities', to='assessments.vulnerabilityscreenshot'),
        ),
        migrations.CreateModel(
            name='AssessmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='assessment_files/')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='assessments.assessmentfile'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessmentpriority'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessmentstatus'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='vulnerabilities',
            field=models.ManyToManyField(blank=True, related_name='vulnerabilities_assessments', to='assessments.assessmentvulnerability'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='who_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
