# Generated by Django 4.2.1 on 2023-08-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='assigned_users',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='close_date',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='expected_end_date',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='files',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='revisions',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='vulnerabilities',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='who_created',
        ),
    ]
