# Generated by Django 4.2.1 on 2023-08-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_a_fields_assessment_assigned_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='af_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
