# Generated by Django 4.2.1 on 2023-08-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_assessment_a_fields_assessment_af_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='expected_end_date',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='summary',
        ),
    ]
