# Generated by Django 4.2.1 on 2023-08-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_remove_assessment_expected_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='close_date',
            new_name='end_date',
        ),
    ]
