# Generated by Django 4.2.1 on 2023-08-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_rename_close_date_assessment_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='created_date',
        ),
        migrations.AddField(
            model_name='assessment',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
