# Generated by Django 4.2.1 on 2023-08-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_remove_assessment_created_date_assessment_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='updated_date',
            new_name='creation_date',
        ),
    ]
