# Generated by Django 4.2.1 on 2023-08-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_rename_updated_date_assessment_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='revisions',
        ),
    ]
