# Generated by Django 4.2.1 on 2023-09-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_taskstatus_assessmenttask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckimageupload',
            name='for_model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ckimageupload',
            name='model_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
