# Generated by Django 4.2.1 on 2023-09-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_ckimageupload_for_model_ckimageupload_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckimageupload',
            name='model_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
