# Generated by Django 4.2.1 on 2023-08-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('s_fields', models.JSONField(blank=True, null=True)),
                ('a_fields', models.JSONField(blank=True, null=True)),
                ('v_fields', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
