# Generated by Django 4.2.1 on 2023-08-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additional_fields',
            old_name='fields',
            new_name='a_fields',
        ),
        migrations.AddField(
            model_name='additional_fields',
            name='v_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
