# Generated by Django 4.2.1 on 2023-08-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_rename_fields_additional_fields_a_fields_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Additional_Fields',
        ),
    ]
