# Generated by Django 4.2.1 on 2023-08-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_delete_additional_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='template',
            name='chart_settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='table_style',
            field=models.FileField(blank=True, null=True, upload_to='templates/table_styles'),
        ),
    ]
