# Generated by Django 4.2.1 on 2023-08-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_remove_template_pdf_file_template_chart_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='table_style',
        ),
    ]
